# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: user_db
      POSTGRES_DB: restapi_dev
    ports:
      - "5437:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"